export const SIGN_IN_REQUEST = 'AUTH_REDUCER::SIGN_IN';
export const SIGN_IN_SUCCESS = 'AUTH_REDUCER::SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'AUTH_REDUCER::SIGN_IN_ERROR';
export const SIGN_UP_REQUEST = 'AUTH_REDUCER::SIGN_UP';
export const SIGN_UP_SUCCESS = 'AUTH_REDUCER::SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'AUTH_REDUCER::SIGN_UP_ERROR';
